name: Publish

on:

  release:
    types: [published]
      
jobs:

  deploy-artifacts:
    name: Deploy artifacts
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Maven repository cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
          
      - name: Set up Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          
      - name: Deploy artifacts to OSSRH
        shell: bash
        run: |
          mvn -B -Possrh-deployer -Pgpg-signer deploy
        env:
          MAVEN_USERNAME: pFO47B0o
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
